#logging:
#  file: zuul_log.txt
server:
  port: 443
  ssl:
    key-store: classpath:api.moontell.cn.jks
    key-store-password: 123456
    keyStoreType: JKS
    keyAlias: api.moontell.cn

spring:
  application:
    name: gateway_zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/,http://peer1:7001/eureka/,http://peer2:7002/eureka/


#设置读取响应超时时间
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000