spring:
  application:
    name: ob_ctrl
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /objectdetect
    publisher-confirms: true
server:
  port: 9000
#logging:
#  file: ob_detect.txt

filepath:
  relative:
    testModelDir:
      tensor_model/objectdetect/models/obdect_model/test/saved_model
